# Dependabot configuration for DQX
# Keeps dependencies up-to-date automatically

version: 2

updates:
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
    open-pull-requests-limit: 5
    reviewers:
      - "phamducnam"  # Add your GitHub username
    labels:
      - "dependencies"
      - "python"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    pull-request-branch-name:
      separator: "/"
    groups:
      # Group all non-major updates together
      non-major:
        update-types:
          - "minor"
          - "patch"
      # Group development dependencies
      dev-dependencies:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
    # DQX-specific rules
    allow:
      # Only allow updates for direct dependencies
      - dependency-type: "direct"
    ignore:
      # Don't update Python itself
      - dependency-name: "python"
      # Be careful with major SymPy updates
      - dependency-name: "sympy"
        update-types: ["version-update:semver-major"]
      # Be careful with major SQLAlchemy updates
      - dependency-name: "sqlalchemy"
        update-types: ["version-update:semver-major"]

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
    open-pull-requests-limit: 5
    reviewers:
      - "phamducnam"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"
      include: "scope"
    groups:
      # Group all GitHub Actions updates
      actions:
        patterns:
          - "*"

  # Docker (if you add Dockerfile in future)
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "build"
      include: "scope"
    # Only check if Dockerfile exists
    ignore:
      - dependency-name: "*"
      # This effectively disables Docker updates until you add a Dockerfile

# Security updates are handled separately and created immediately
# regardless of the schedule when vulnerabilities are detected
