# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json

# CodeRabbit Configuration
# AI-powered code review for DQX

# Language settings
language: "en-US"

# Review settings
reviews:
  # Enable high-quality reviews
  high_level_summary: true
  poem: false  # Disable poem generation
  review_status: true
  collapse_walkthrough: false

  # Request changes for critical issues
  request_changes_workflow: true

  # Auto-review on PR open/update
  auto_review:
    enabled: true
    drafts: false  # Don't review draft PRs
